<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MASA.InvoiceSystem.Domain\MASA.InvoiceSystem.Domain.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>MASA.InvoiceSystem.Application</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

</Project>
